---
title: "lofthf-scripts"
output: html_notebook
---
```{r}
library(tidyr)
library(dplyr)
setwd("/VOLUMES/BWH-SLEEPEPI-LOFT/Data/SAS/_FINAL/30-Datasets")

# rbind the dataset with same prefixes: 
prefixes <- c("anthropometry", "eq5d", "hq", "kccq", "phq8", "promis")
timepoints <- c("base", "6mo", "12mo")

# combine datasets for each prefix
combine_datasets <- function(prefix) {
  datasets <- list()
  for(time in timepoints) {
    filename <- paste0(prefix, "_", time, ".csv")
    data <- read.csv(filename, stringsAsFactors = FALSE)
    datasets[[time]] <- data
  }
  combined <- do.call(rbind, datasets)
  return(combined)
}

# now all datasets with *base, 6mon, and 12mon are in combined*data list
combined_data <- lapply(prefixes, combine_datasets)
names(combined_data) <- prefixes

# merge all datasets in combined_data by "subject", "timepoint", "site"
merged_data <- combined_data[[1]]
for(i in 2:length(combined_data)) {
  merged_data <- merge(merged_data, combined_data[[i]], 
                      by = c("subject", "timepoint", "site"),
                      all = TRUE)
}

# add psg and subinfo datasets
psg <- read.csv("/Volumes/BWH-SLEEPEPI-LOFT/Data/SAS/_FINAL/30-Datasets/psg/loftpsg_nsrr.csv", stringsAsFactors = FALSE)
subinfo <- read.csv("subinfo.csv", stringsAsFactors = FALSE)

# screening (psg_study_type = 1) and 12-month visit (psg_study_type = 2)
psg$timepoint <- ifelse(psg$psg_study_type == 1, 0, 
                       ifelse(psg$psg_study_type == 2, 3, NA))

subinfo$timepoint <- 0

site_lookup <- unique(subinfo[, c("subject", "site")])

# add site column to psg data based on subject
psg <- merge(psg, site_lookup, by = "subject", all.x = TRUE)

# merge PSG with merged_data 
final_data <- merge(merged_data, psg,
                   by = c("subject", "timepoint", "site"),
                   all = TRUE)

# add subinfo dataset
final_data <- merge(final_data, subinfo,
                   by = c("subject", "timepoint", "site"),
                   all = TRUE)

# a few variables doesn't have dd. remove them
variables_to_remove <- c("eq_index", "i1", "u","subinfo_last_visit_completed","promis_sd_sum_m","promis_sri_sum_m")
final_data <- final_data[, !names(final_data) %in% variables_to_remove]

# rename long variable names
rename_map <- c(
  "promis_sri_sleepy_daytime" = "promis_sri_sleepy",
  "promis_sri_concentrating" = "promis_sri_conc",
  "promis_sri_alert_when_woke" = "promis_sri_alert",
  "promis_sri_irritable" = "promis_sri_irrit",
  "promis_sri_tired" = "promis_sri_tired",
  "promis_sri_problems_poor_sleep" = "promis_sri_prob",
  "promis_sri_trouble_staying_awake" = "promis_sri_awake",
  "promis_sri_getting_things_done" = "promis_sri_done",
  "promis_sd_satisfied_with_sleep" = "promis_sd_satis",
  "promis_sd_sleep_refreshingr" = "promis_sd_refr_r",
  "promis_sd_diff_falling_asleep" = "promis_sd_fall",
  "promis_sd_sleep_refreshing" = "promis_sd_refr",
  "promis_sd_satisfied_with_sleepr" = "promis_sd_satis_r",
  "promis_sd_sleep_restless" = "promis_sd_restl",
  "subinfo_how_info_obtained_2" = "info_obt2",
  "subinfo_how_info_obtained_1" = "info_obt1",
  "eq5d_anxiety_depression" = "eq5d_anx",
  "kccq_swelling_bothersome" = "kccq_swl1",
  "kccq_swelling_when_waking" = "kccq_swl2",
  "kccq_visiting_family_friends" = "kccq_visit",
  "kccq_intimate_relationships" = "kccq_intim",
  "kccq_hobbies" = "kccq_hobby",
  "kccq_household_chores" = "kccq_chore",
  "kccq_feeling_living_hf_for_life" = "kccq_life"
)


for(old_name in names(rename_map)) {
  if(old_name %in% names(final_data)) {
    names(final_data)[names(final_data) == old_name] <- rename_map[old_name]
  }
}

# Impute missing site values from first 2 digits of subject
final_data$site <- ifelse(is.na(final_data$site) | final_data$site == "", 
                          substr(final_data$subject, 1, 2), 
                          final_data$site)

write.csv(final_data, "/VOLUMES/BWH-SLEEPEPI-LOFT/nsrr-prep/0.1.0.pre/lofthf-dataset.0.1.0.pre.csv", row.names = FALSE, na = '')
```


# harmonized dataset
```{r}
harmonized_data<-final_data[,c("subject","timepoint", "subinfo_current_age", "anthro_bp_pe_bmi", "subinfo_ethnicity", "subinfo_race", 
                             "subinfo_sex", "anthro_bp_pe_diastolic_1","anthro_bp_pe_diastolic_2","anthro_bp_pe_diastolic_3","anthro_bp_pe_systolic_1","anthro_bp_pe_systolic_2","anthro_bp_pe_systolic_3","hq_ever_smoked_cigarettes")]%>%
  dplyr::mutate(nsrrid=subject,
                nsrr_age=subinfo_current_age,
                nsrr_bmi=anthro_bp_pe_bmi,
                nsrr_bp_diastolic=(anthro_bp_pe_diastolic_1+anthro_bp_pe_diastolic_2+anthro_bp_pe_diastolic_3)/3,
                nsrr_bp_systolic=(anthro_bp_pe_systolic_1+anthro_bp_pe_systolic_2+anthro_bp_pe_systolic_3)/3,
                nsrr_race=dplyr::case_when(
                  subinfo_race==1 ~ "american indian or alaska native",
                  subinfo_race==2 ~ "asian",
                  subinfo_race==3 ~ "native hawaiian or other pacific islander",
                  subinfo_race==4 ~ "black or african american",
                  subinfo_race==5 ~ "white",
                  subinfo_race==6 ~ "other",
                  TRUE ~ "not reported"
                ),
                nsrr_sex=dplyr::case_when(
                  subinfo_sex==1 ~ "male",
                  subinfo_sex==2 ~ "female",
                  TRUE ~ "not reported"
                ),
                nsrr_ethnicity=dplyr::case_when(
                  subinfo_ethnicity==1 ~ "hispanic or latino",
                  subinfo_ethnicity==2 ~ "not hispanic or latino",
                  TRUE ~ "not reported"
                ),
                nsrr_ever_smoker=dplyr::case_when(
                  hq_ever_smoked_cigarettes==2 ~ "no",
                  hq_ever_smoked_cigarettes==1 ~ "yes",
                  TRUE ~ "not reported"
                ))%>%
  select(nsrrid,timepoint, nsrr_age,nsrr_race,nsrr_ethnicity,nsrr_sex,nsrr_bmi,nsrr_bp_diastolic,nsrr_bp_systolic,nsrr_ever_smoker)

psg_variables <- final_data %>%
  select(ahi, cai, oai, avg_pulse, avg_spo2, min_spo2, odi, spo2_90, spo2_88, spo2_85,slp_efficiency, slp_latency, total_slp_time, arousal_index, n1_percent,n2_percent,n3_percent, rem_percent, psg_overall_study_quality, psg_score_sleep_wake_only) %>%
  rename(nsrr_ahi_hp3u=ahi,
         nsrr_cai=cai,
         nsrr_oai=oai,
         nsrr_avglvlhr=avg_pulse,
         nsrr_avglvlsa=avg_spo2,
         nsrr_minlvlsa=min_spo2,
         nsrr_odi_dsge3=odi,
         nsrr_pctdursp_salt90=spo2_90,
         nsrr_pctdursp_sale88=spo2_88,
         nsrr_pctdursp_salt85=spo2_85,
         nsrr_ttleffsp_f1=slp_efficiency,
         nsrr_ttllatsp_f1=slp_latency,
         nsrr_tst_f1=total_slp_time,
         nsrr_phrnumar=arousal_index,
         nsrr_pctdursp_s1=n1_percent,
         nsrr_pctdursp_s2=n2_percent,
         nsrr_pctdursp_s3=n3_percent,
         nsrr_pctdursp_sr=rem_percent,
         nsrr_flag_quality=psg_overall_study_quality,
         nsrr_flag_spsw = psg_score_sleep_wake_only,
         )%>%
  mutate(nsrr_flag_spsw=dplyr::case_when(
    nsrr_flag_spsw==0 ~ "full scoring",
    nsrr_flag_spsw==1 ~ "sleep/wake only",
    TRUE ~ "unknown"
  ))

harmonized_data <- bind_cols(harmonized_data, psg_variables)

write.csv(harmonized_data, "/VOLUMES/BWH-SLEEPEPI-LOFT/nsrr-prep/0.1.0.pre/lofthf-harmonized-dataset.0.1.0.pre.csv", row.names = FALSE, na = '')

```

